# docker run -p 80:80 lindsay-static-assets
# docker build . -f Dockerfile.StaticAssets -t lindsay-static-assets

FROM nginx

RUN adduser --system --no-create-home --shell /bin/false --group --disabled-login www

RUN mkdir /etc/nginx/logs
RUN chown -P www /etc/nginx/logs 

RUN touch /etc/nginx/logs/error.log
RUN touch /etc/nginx/logs/nginx.pid

COPY ./assets/ /usr/share/nginx/static_assets/
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN chown -P www /usr/share/nginx/static_assets