# docker run lindsay-ingress -p 80:80
# docker build . -f Dockerfile.NginxIngress -t lindsay-ingress
ARG ARCH=arm64

FROM ${ARCH}/nginx

RUN adduser --system --no-create-home --shell /bin/false --group --disabled-login www

RUN mkdir /etc/nginx/logs
RUN chown -P www /etc/nginx/logs 

RUN touch /etc/nginx/logs/error.log
RUN touch /etc/nginx/logs/nginx.pid

COPY ./nginx.conf /etc/nginx/nginx.conf