name: CI
on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Backend Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Bootstrap and setup environment
      run: ./setup.sh   

    - name: Run Unit Testing
      run: cd backend && ./test/scripts/unit_tests.sh
      
