name: CI
on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]
        python-version: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup Python Environment
      run: ./backend/scripts/setup.sh
      
      
