name: CI
on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x]
        python-version: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Bootstrap and setup environment
      run: ./setup.sh
    
    - name: Run Unit Testing
      run: ./test.sh
      
