name: CORE Frontend Unit Testing
on:  
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Unit Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Bootstrap and setup environment
      working-directory: ./frontend/lindsay-wildlife-treasure-hunt-frontend
      run: ./scripts/setup.sh   

    - name: Execute Tests
      working-directory: ./frontend/lindsay-wildlife-treasure-hunt-frontend
      run: ./test/scripts/unit_tests.sh  
      